/*REPORTE DE RECETAS*/
drop view if exists reporteTotalRecetas;
create view reporteTotalRecetas as
SELECT DESCRIPCION,GRUPO_ALIMENTICIO,INFORMACION_NUTRICIONAL
FROM INGREDIENTE,RECETA 
WHERE INGREDIENTE.ID_RECETA = RECETA.ID_RECETA;

select * from reporteTotalRecetas;

/*LISTA DE USUARIOS*/
drop view if exists ListaDeUsuarios;
create view ListaDeUsuarios as
SELECT ID_USUARIO,NOMBRE,APELLIDO 
FROM USUARIO;

select * from ListaDeUsuarios;

/*MENUS*/

drop view if exists MENUS;
create view MENUS as
SELECT USUARIO.ID_USUARIO, RECETA.DESCRIPCION, RECETA.INFORMACION_NUTRICIONAL, INGREDIENTE.GRUPO_ALIMENTICIO, TABLERO_SEMANAL.FRANJA_HORARIA
FROM USUARIO, RECETA, INGREDIENTE, TABLERO_SEMANAL 
WHERE USUARIO.ID_USUARIO = RECETA.ID_USUARIO and RECETA.ID_RECETA = INGREDIENTE.ID_RECETA and TABLERO_SEMANAL.ID_USUARIO = USUARIO.ID_USUARIO;
select * from MENUS;

/*Recetas con más de 200 calorías. */
DROP VIEW IF EXISTS RECETA_200;
CREATE VIEW RECETA_200 AS 
SELECT DESCRIPCION, INFORMACION_NUTRICIONAL FROM RECETA
WHERE INFORMACION_NUTRICIONAL>200;
 
 /*Mostrar datos del usuario*/
 drop view if exists informacionUsuario;
create view informacionUsuario as
SELECT * 
FROM USUARIO;

/*Mostrar metas cumplidas. */
DROP VIEW IF EXISTS METAS_CUMPLIDAS;
CREATE VIEW METAS_CUMPLIDAS AS 
SELECT ID_META, FECHA_INICIO_M, FECHA_FIN_M FROM META 
WHERE  META_CUMPLIDA=TRUE ;


/*Mostrar resumen semanal.*/
drop view if exists ResumenSemanal;
create view ResumenSemanal as
SELECT RE.CALORIAS_CONSUMIDAS_KCAL, RE.CALORIAS_REDUCIDAS_KCAL, U.NOMBRE, U.APELLIDO
FROM RESUMEN_SEMANAL RE,USUARIO U WHERE U.ID_USUARIO=RE.ID_USUARIO;

/*Mostrar un registro calorías consumidas mayor a 800.*/
DROP VIEW IF EXISTS USUARIO_CON_MAS_800;
CREATE VIEW USUARIO_CON_MAS_800 AS
SELECT U.ID_USUARIO, U.NOMBRE, U.APELLIDO, RE.CALORIAS_CONSUMIDAS_KCAL 
FROM USUARIO U , RESUMEN_SEMANAL RE WHERE U.ID_USUARIO=RE.ID_USUARIO 
AND RE.CALORIAS_CONSUMIDAS_KCAL>800;

/*Mostrar un registro de los usuarios que consumieron 700 cal en la semana*/
DROP VIEW IF EXISTS CAL_700;
CREATE VIEW CAL_700 AS 
SELECT NUMERO_RESUMEN,ID_USUARIO FROM RESUMEN_SEMANAL WHERE CALORIAS_CONSUMIDAS_KCAL=700;

/*Mostrar el grupo alimenticio de los ingredientes que no superen las 150 calorías.*/
DROP VIEW IF EXISTS ING_MENOS_150;
CREATE VIEW ING_MENOS_150 AS 
SELECT ID_INGREDIENTE,GRUPO_ALIMENTICIO FROM INGREDIENTE WHERE CALORIAS<150;

/* Mostrar tablero semanal*/
drop view if exists TableroSemanal;
create view TableroSemanal as
SELECT *
FROM TABLERO_SEMANAL;

/*Mostrar ingredientes de una receta con menos de 450 calorías.*/
DROP VIEW IF EXISTS ING_RECETA_MENOS_450;
CREATE VIEW ING_RECETA_MENOS_450 AS
SELECT I.ID_INGREDIENTE, R.DESCRIPCION FROM INGREDIENTE I, RECETA R
WHERE I.ID_RECETA=R.ID_RECETA AND R.INFORMACION_NUTRICIONAL<450;

/*Mostrar el ID de los usuarios que han consumido más de 1000 calorías semanalmente.*/
drop view if exists UsuarioConConsumoMas1000;
create view UsuarioConConsumoMas1000 as
SELECT U.ID_USUARIO FROM USUARIO U, RESUMEN_SEMANAL RE
WHERE RE.ID_USUARIO = U.ID_USUARIO AND CALORIAS_CONSUMIDAS_KCAL > 1000;
select * from UsuarioConConsumoMas1000;

/*Cantidad de metas cumplidas del usuario.*/
DROP VIEW IF EXISTS METAS_USUARIO;
CREATE VIEW METAS_USUARIO AS 
SELECT COUNT(M.ID_META) AS MetasCumplidas, U.NOMBRE FROM META M, USUARIO U, RESUMEN_SEMANAL RE
WHERE M.NUMERO_RESUMEN=RE.NUMERO_RESUMEN AND RE.ID_USUARIO=U.ID_USUARIO GROUP BY U.NOMBRE;
